added prepare_media, more checks for snapshot availability, code cleanup

diff --git a/pbs-zfs-backup b/pbs-zfs-backup
--- a/pbs-zfs-backup
+++ b/pbs-zfs-backup
@@ -1,6 +1,6 @@
 #!/bin/bash
 set -o errtrace
-trap 'echo ERROR: Fehler in Funktion "$FUNCNAME", Errorcode "$?" ; exit 1' ERR
+trap 'echo ERROR: Fehler in Funktion "${FUNCNAME[0]}", Errorcode "$?" ; exit 1' ERR
 
 #set -xv
 
@@ -9,6 +9,7 @@ echo "$0" - a PBS ZFS datastore to USB media sync tool
 # default settings
 backup_sourceZfs=PBS-WD-2TB-intern
 backup_snapshot_basename=pbs-backupsnap
+new_backup_media_basename=nbp-proxmox-backup_$(date +%Y%m%d-%H%M%S)_0
 
 # ---------------------
 
@@ -33,11 +34,12 @@ cleanup_and_exit () {
 read_snapshot_tracker_db () {
 	unset lowest_snapshot_number
 	[[ -f snapshot_tracker.db ]] || return 1
-	while read drivename snapshot_number ; do
+	while read -r drivename snapshot_number ; do
 	snapshot_tracker[$drivename]=$snapshot_number
-	[[ -z $lowest_snapshot_number || $snapshot_number < $lowest_snapshot_number ]] && lowest_snapshot_number=$snapshot_number
-	done <snapshot_tracker.db 
-	log "$0 -> lowest_snapshot_number is $lowest_snapshot_number"
+	if [[ -z $lowest_snapshot_number || $snapshot_number -lt $lowest_snapshot_number ]] ; then
+	       lowest_snapshot_number=$snapshot_number
+	fi
+	done < snapshot_tracker.db
 }
 
 write_snapshot_tracker_db () {
@@ -48,11 +50,11 @@ write_snapshot_tracker_db () {
 	read_snapshot_tracker_db
 }
 
-prepare_empty_media () {
-	wipefs -a "$backupDrive" &&\
-	zpool create -m /"$backup_targetZfs" -o ashift=12 "$backup_targetZfs" "$backupDrive" &&\
-	zfs set canmount=noauto com.sun:auto-snapshot=false "$backup_targetZfs"\
-	;
+prepare_media () {
+	wipefs -a /dev/disk/by-id/"$backup_media_name" &&\
+	zpool create -o ashift=12 ${new_backup_media_basename} /dev/disk/by-id/"$backup_media_name" &&\
+	zfs set canmount=noauto com.sun:auto-snapshot=false ${new_backup_media_basename}
+	backup_targetZfs=${new_backup_media_basename}
 }
 
 list_snapshots () {
@@ -70,42 +72,54 @@ resume_send () {
 }
 
 identify_backup_media () {
-	diff fixed_disks.list <(ls /dev/disk/by-id) | tail -n +2 | awk '{if ( $NF !~ /part[0-9]+$/ ) {print $NF} }'
+	#diff fixed_disks.list <(ls /dev/disk/by-id) | tail -n +2 | awk '{if ( $NF !~ /part[0-9]+$/ ) {print $NF} }'  <-- TOO DANGEROUS
+	for media in $(awk '{print $1}' <snapshot_tracker.db) ; do
+		if [[ -L /dev/disk/by-id/"$media" ]] ; then 
+		       echo $media
+		       break
+		fi	       
+	done
+
 }
 
 detect_backup_pool () {
 # INPUT: none
 # OUTPUT: ZFS poolname
 	for hdd in $(awk '{print $1}' <backup_media.db) ; do
-		for partition in /dev/disk/by-id/"$hdd"*part* ; do
+		for partition in /dev/disk/by-id/${hdd}-part* ; do
 			zpool import -o name -d "$partition" 2>/dev/null | awk '{if($1 ~ /pool:/){print $2}}'
 		done
 	done
 }
 
-get_last_backup_snapshot () {
+get_last_backup_snapshot_name () {
 # IN : ZFS file system
-# OUT: last backup snapshot
+# OUT: last backup snapshot name
 	zfs list -o name -H -s creation -t snapshot "$1"  | tail -n 1 | awk -F @ '{print $2}'
+}
+get_last_backup_snapshot_number () {
+# IN : ZFS file system
+# OUT: last backup snapshot number
+	zfs list -o name -H -s creation -t snapshot "$1"  | tail -n 1 | awk -F _ '{print $NF}' | grep -E '^[0-9]+$'
 }
 
 remove_old_snapshots () {
 	[[ -z $1 ]] && return 1
 	if [[ $1 == $backup_sourceZfs ]] ; then
-		# read snapshot_tracker and remove all from backup_sourceZfs but oldest one existing on any backup media 
+		# read snapshot_tracker and remove all from backup_sourceZfs but oldest TWO existing on any backup media 
 		for snap in $(list_snapshots "$1" | awk '{ match($0, /[0-9]+$/) ; print substr ($0,RSTART,RLENGTH) }') ; do
-			if [[ $snap < $lowest_snapshot_number ]] ; then
-				log "removing ${backup_sourceZfs}@${backup_snapshot_basename}_$snap..."
-				echo "zfs destroy ${backup_sourceZfs}@${backup_snapshot_basename}_$snap"
-				log "... done"
+			if [[ $(($snap+1)) < $lowest_snapshot_number ]] ; then
+				log "removing ${backup_sourceZfs}@${backup_snapshot_basename}_$snap . ."
+				echo zfs destroy ${backup_sourceZfs}@${backup_snapshot_basename}_$snap
+				log ". . done"
 			fi
 		done
 	else
-		# remove all but last snapshot from backup media
-		for snap in $(list_snapshots "$1" | head -n -1) ; do 
-			log "removing ${backup_targetZfs}@$snap..."
-			echo "zfs destroy ${backup_targetZfs}@$snap"
-			log "... done"
+		# remove all but last 2 snapshot from backup media
+		for snap in $(list_snapshots "$1" | head -n -2) ; do 
+			log "removing ${backup_targetZfs}@$snap . ."
+			zfs destroy ${backup_targetZfs}@$snap
+			log ". . done"
 		done
 
 	fi
@@ -115,7 +129,13 @@ remove_old_snapshots () {
 do_incremental_send () {
 # INPUT: $1 ->  ZFS start snapshot ; $2 -> ZFS end snapshot
 # OUTPUT: none (+ update snapshot_tracker)
-	zfs send -V "$backup_sourceZfs"@"$2" -i @"$1" | zfs recv -sFv "$backup_targetZfs" && snapshot_tracker[$backup_media_name]=$(echo "$2" | awk -F _ '{print $2}')
+	zfs send -V "$backup_sourceZfs"@"$2" -i @"$1" | zfs recv -sFv "$backup_targetZfs" && snapshot_tracker[$backup_media_name]=$(echo "$2" | awk -F _ '{print $NF}')
+}
+
+do_full_send () {
+# INPUT: $1 ->  ZFS snapshot
+# OUTPUT: none (+ update snapshot_tracker)
+	zfs send -V "$backup_sourceZfs"@"$1" | zfs recv -sFv "$backup_targetZfs" && snapshot_tracker[$backup_media_name]=$(echo "$1" | awk -F _ '{print $NF}')
 }
 
 get_resume_token () {
@@ -140,10 +160,17 @@ detect_inserted_backuppool () {
 	done
 }
 
+check_snapshot () {
+# IN : ZFS filesystem, ZFS snapshot
+# OUT: ZFS snapshot (if found) or empty response
+	zfs list -t snap "$1"@"$2" -H -o name 2>/dev/null
+}
 
 
 
 #-#-#-#-#-#-#-#-#-#-# MAIN #-#-#-#-#-#-#-#-#-#-#-#-#
+
+read_snapshot_tracker_db
 
 # identify backup media
 log "Suche Backupmedium . . ."
@@ -166,25 +193,19 @@ else
 	# identify backup pool on backup media
 	backup_targetZfs=$(detect_backup_pool)
 	if [[ -z $backup_targetZfs ]] ; then 
-		log ". . . kein importierbarer Backup-Pool gefunden" 
-		exit 1
+		log ". . . kein importierbarer Backup-Pool auf $backup_media_name gefunden. Erzeuge ZFS-Filesystem . ." 
 		########## prepare new backup media with new zpool (zpool create)
+		prepare_media
+		log ". . ok. ($backup_targetZfs)"
+		exit
 	else
        		log Backup-Pool ist "$backup_targetZfs"
-		log "Importiere $backup_targetZfs . ."
-		zpool import "$backup_targetZfs"
+		log "Importiere $backup_targetZfs von /dev/disk/by-id/${backup_media_name}-part1 . ."
+		zpool import ${backup_targetZfs} -d /dev/disk/by-id/${backup_media_name}-part1
 		log '. . fertig'
 	fi
 fi
 
-
-# ---- TESTING below----
-
-#read_snapshot_tracker_db
-#remove_old_snapshots $backup_targetZfs
-#remove_old_snapshots $backup_sourceZfs
-
-# ----- TESTING above------
 
 log "Resume Token auf $backup_targetZfs vorhanden? . ." 
 resume_token=$(get_resume_token "$backup_targetZfs")
@@ -202,27 +223,37 @@ fi
 # read snapshot_tracker.db into associative array snapshot_tracker[]
 read_snapshot_tracker_db
 
-zfs_target_snap=$(get_last_backup_snapshot "$backup_sourceZfs")
-zfs_incremental_snap=$(get_last_backup_snapshot "$backup_targetZfs")
+zfs_target_snap=$(get_last_backup_snapshot_name "$backup_sourceZfs")
+zfs_incremental_snap=$(get_last_backup_snapshot_name "$backup_targetZfs")
 
-
+# do ZFS send operation
 if [[ $zfs_incremental_snap == $zfs_target_snap ]] ; then
 	log "aktuellster Snapshot $zfs_target_snap auf Backupmedium vorhanden, nichts zu tun"
+elif [[ -z $zfs_incremental_snap ]] ; then
+	log "Kein Snapshot auf Backupmedium, sende komplettes Filesystem . ."
+	prepare_media
+	do_full_send $zfs_target_snap
+	log ". . ok"
+# Source ZFS has last snapshot of target ZFS?	
+elif [[ -z $(check_snapshot "$backup_sourceZfs" "$zfs_incremental_snap") ]] ; then
+	log "letzter Snapshot auf Backupmedium fehlt in Quell-ZFS -> Full Send"
+	log "exportiere Pool $backup_targetZfs . ."
+	zpool export $backup_targetZfs
+	log ". . ok"
+	log "neues ZFS auf Backupmedium erzeugen . ."
+	prepare_media
+	log ". . ok ($backup_targetZfs)"
+	log "Sende komplettes ZFS-Filesystem (${backup_sourceZfs}@${zfs_target_snap} -> $backup_targetZfs)"
+	do_full_send "$zfs_target_snap"
+	log ". . ok"
 else
-	if [[ -z $zfs_incremental_snap ]] ; then
-		log "Kein Snapshot auf Backupmedium, sende komplettes Filesystem... (TODO!)"
-		#do_full_send (send full ZFS stream)
-	else
-		log "Sende inkrementellen ZFS stream . . ($zfs_incremental_snap -> $zfs_target_snap)"
-		snapshot_tracker[$backup_media_name]=$(echo "$zfs_incremental_snap" | awk -F _ '{print $2}')
-		do_incremental_send $zfs_incremental_snap $zfs_target_snap
-		log ". .  fertig"
-	fi
-
+	log "Sende inkrementellen ZFS stream . . ($zfs_incremental_snap -> $zfs_target_snap)"
+	snapshot_tracker[$backup_media_name]=$(echo "$zfs_incremental_snap" | awk -F _ '{print $NF}')
+	do_incremental_send $zfs_incremental_snap $zfs_target_snap
+	log ". . ok"
 fi
 
-#write snapshot_tracker.db
-#snapshot_tracker[$backup_media_name]=$(echo "$zfs_target_snap" | awk -F _ '{print $2}') --> moved to do_incremental_send()
+
 write_snapshot_tracker_db
 
 remove_old_snapshots $backup_targetZfs
